/* eslint-disable camelcase */
const first_type = [
  {
    src_house: require('../../common/images/house1.jpg'),
    classNUM: 'one',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house1.jpg'),
    classNUM: 'two',
    introduce_name: '时代香海彼岸',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '免费专车',
    tag_three: '品牌房企',
    tag_four: '地铁沿线',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house1.jpg'),
    classNUM: 'three',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    typetag_one: '在售',
    typetag_two: '住宅'
    // tag_four: '开发区'
  },
  {
    src_house: require('../../common/images/house1.jpg'),
    classNUM: 'four',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house1.jpg'),
    classNUM: 'five',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house1.jpg'),
    classNUM: 'one',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house1.jpg'),
    classNUM: 'one',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house1.jpg'),
    classNUM: 'one',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house1.jpg'),
    classNUM: 'one',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house1.jpg'),
    classNUM: 'one',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house1.jpg'),
    classNUM: 'one',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house1.jpg'),
    classNUM: 'one',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house1.jpg'),
    classNUM: 'one',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house1.jpg'),
    classNUM: 'one',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  }
]
const second_type = [
  {
    src_house: require('../../common/images/house5.jpg'),
    classNUM: 'one',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house5.jpg'),
    classNUM: 'two',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house5.jpg'),
    classNUM: 'three',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house5.jpg'),
    classNUM: 'four',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house5.jpg'),
    classNUM: 'five',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  }
]
const third_type = [
  {
    src_house: require('../../common/images/house6.jpg'),
    classNUM: 'one',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house6.jpg'),
    classNUM: 'two',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house6.jpg'),
    classNUM: 'three',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house6.jpg'),
    classNUM: 'four',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house6.jpg'),
    classNUM: 'five',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  }
]
const four_type = [
  {
    src_house: require('../../common/images/house7.jpg'),
    classNUM: 'one',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house7.jpg'),
    classNUM: 'two',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house7.jpg'),
    classNUM: 'three',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house7.jpg'),
    classNUM: 'four',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  },
  {
    src_house: require('../../common/images/house7.jpg'),
    classNUM: 'five',
    introduce_name: '金科集美御峰',
    house_type: '户型：3室/4室',
    price: ' 22000元/平(均价)',
    total_price: '总价200万元/套',
    details_content: '南沙/黄阁/建面82-115m² ',
    tag_one: '在售',
    tag_two: '品牌房企',
    tag_three: '贴心物业',
    tag_four: '开发区',
    typetag_one: '在售',
    typetag_two: '住宅'
  }
]
export { first_type, second_type, third_type, four_type }
